version: '3'
services:
  nginx:
    image: nginx
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    environment:
    - NGINX_PORT=80
